lane :beta do
  gradle(task: 'assemble', build_type: 'Release', flavor: 'prod')
  aab_path = File.expand_path("../build/app/outputs/bundle/prodRelease/app-prod-release.aab", __dir__)
  upload_to_play_store(track: 'beta', aab: aab_path)
end